pipeline {
    agent any
    environment{
        VERSION = "${env.BUILD_ID}"
    }
    stages{
        stage("sonar quality check"){
            agent {
                label 'kube-slave'
            }
            steps{
                script{
                    dir('invoice/') {
                        // withSonarQubeEnv(credentialsId: 'sonar-token') {
                            sh 'chmod +x gradlew'
                            sh './gradlew test integrationTest jacocoTestReport'
                            sh './gradlew -Pprod -Pwar clean bootWar'
                    }

                }
            }
        }
    }

}
